apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      containers:
        - name: mkdocs
          image: squidfunk/mkdocs-material
          ports:
            - containerPort: 8000
          volumeMounts:
           - name: docs
             mountPath: /docs
      volumes:
       - name: docs
         hostPath:
           path: /home/user/Linux_device_manager/server/samba/memo
