# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "$(openssl rand -hex 32)"  # change this!
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
  # https://github.com/searxng/searxng/blob/master/searx/settings.yml
  port: 8081
  bind_address: "0.0.0.0"
redis:
  url: redis://redis:6379/0


# Memo: settins.yml(Plural)