# https://grafana.com/docs/grafana/latest/administration/provisioning/
apiVersion: 1

datasources:
  # - name: Prometheus
  #  type: prometheus
  #  access: proxy
  #  url: http://prometheus:9090
  #  isDefault: true
  -
  - name: Mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    jsonData:
      prometheusType: Mimir

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

# Do not forget multi tenant http header