auth_enabled: false

# https://grafana.com/docs/loki/latest/configure/
# A. Server
server:
  http_listen_port: 3100

# B. 
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  # Assign Loki Node
  ring:
    # Where to store the ring info(Key-Value Store)
    kvstore:
      store: memberlist

# C. schema_config
# Log Index, Version
schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# D. storage_config
storage_config:
  filesystem:
    directory: /loki/chunks


# E. limits_config
limits_config:
  retention_period: 168h 

# F. auth_enabled